/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Generation = IDL.Nat;
export const QuizConfig = IDL.Record({
  'generation' : IDL.Opt(Generation),
  'questionCount' : IDL.Nat,
});
export const SessionStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
});
export const QuestionKind = IDL.Variant({
  'guessMove' : IDL.Null,
  'guessName' : IDL.Null,
  'guessType' : IDL.Null,
});
export const QuestionView = IDL.Record({
  'id' : IDL.Nat,
  'kind' : QuestionKind,
  'prompt' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'pokemonId' : IDL.Nat,
});
export const SessionView = IDL.Record({
  'id' : IDL.Nat,
  'status' : SessionStatus,
  'questions' : IDL.Vec(QuestionView),
});
export const SessionId = IDL.Nat;
export const ScoreResult = IDL.Record({
  'total' : IDL.Nat,
  'score' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const AnswerResult = IDL.Record({
  'correctIndex' : IDL.Nat,
  'correct' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func([QuizConfig], [SessionView], []),
  'getScore' : IDL.Func([SessionId], [IDL.Opt(ScoreResult)], ['query']),
  'getSession' : IDL.Func([SessionId], [IDL.Opt(SessionView)], ['query']),
  'submitAnswer' : IDL.Func(
      [SessionId, IDL.Nat, IDL.Nat],
      [IDL.Opt(AnswerResult)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Generation = IDL.Nat;
  const QuizConfig = IDL.Record({
    'generation' : IDL.Opt(Generation),
    'questionCount' : IDL.Nat,
  });
  const SessionStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
  });
  const QuestionKind = IDL.Variant({
    'guessMove' : IDL.Null,
    'guessName' : IDL.Null,
    'guessType' : IDL.Null,
  });
  const QuestionView = IDL.Record({
    'id' : IDL.Nat,
    'kind' : QuestionKind,
    'prompt' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'pokemonId' : IDL.Nat,
  });
  const SessionView = IDL.Record({
    'id' : IDL.Nat,
    'status' : SessionStatus,
    'questions' : IDL.Vec(QuestionView),
  });
  const SessionId = IDL.Nat;
  const ScoreResult = IDL.Record({
    'total' : IDL.Nat,
    'score' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const AnswerResult = IDL.Record({
    'correctIndex' : IDL.Nat,
    'correct' : IDL.Bool,
  });
  
  return IDL.Service({
    'createSession' : IDL.Func([QuizConfig], [SessionView], []),
    'getScore' : IDL.Func([SessionId], [IDL.Opt(ScoreResult)], ['query']),
    'getSession' : IDL.Func([SessionId], [IDL.Opt(SessionView)], ['query']),
    'submitAnswer' : IDL.Func(
        [SessionId, IDL.Nat, IDL.Nat],
        [IDL.Opt(AnswerResult)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };