/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerResult { 'correctIndex' : bigint, 'correct' : boolean }
export type Generation = bigint;
export type QuestionKind = { 'guessMove' : null } |
  { 'guessName' : null } |
  { 'guessType' : null };
export interface QuestionView {
  'id' : bigint,
  'kind' : QuestionKind,
  'prompt' : string,
  'options' : Array<string>,
  'pokemonId' : bigint,
}
export interface QuizConfig {
  'generation' : [] | [Generation],
  'questionCount' : bigint,
}
export interface ScoreResult {
  'total' : bigint,
  'score' : bigint,
  'percentage' : bigint,
}
export type SessionId = bigint;
export type SessionStatus = { 'active' : null } |
  { 'completed' : null };
export interface SessionView {
  'id' : bigint,
  'status' : SessionStatus,
  'questions' : Array<QuestionView>,
}
export interface _SERVICE {
  'createSession' : ActorMethod<[QuizConfig], SessionView>,
  'getScore' : ActorMethod<[SessionId], [] | [ScoreResult]>,
  'getSession' : ActorMethod<[SessionId], [] | [SessionView]>,
  'submitAnswer' : ActorMethod<
    [SessionId, bigint, bigint],
    [] | [AnswerResult]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];