/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuestionView {
    id: bigint;
    kind: QuestionKind;
    prompt: string;
    options: Array<string>;
    pokemonId: bigint;
}
export interface ScoreResult {
    total: bigint;
    score: bigint;
    percentage: bigint;
}
export type Generation = bigint;
export type SessionId = bigint;
export interface QuizConfig {
    generation?: Generation;
    questionCount: bigint;
}
export interface SessionView {
    id: bigint;
    status: SessionStatus;
    questions: Array<QuestionView>;
}
export interface AnswerResult {
    correctIndex: bigint;
    correct: boolean;
}
export enum QuestionKind {
    guessMove = "guessMove",
    guessName = "guessName",
    guessType = "guessType"
}
export enum SessionStatus {
    active = "active",
    completed = "completed"
}
export interface backendInterface {
    createSession(config: QuizConfig): Promise<SessionView>;
    getScore(sessionId: SessionId): Promise<ScoreResult | null>;
    getSession(sessionId: SessionId): Promise<SessionView | null>;
    submitAnswer(sessionId: SessionId, questionIndex: bigint, chosenIndex: bigint): Promise<AnswerResult | null>;
}
import type { AnswerResult as _AnswerResult, Generation as _Generation, QuestionKind as _QuestionKind, QuestionView as _QuestionView, QuizConfig as _QuizConfig, ScoreResult as _ScoreResult, SessionStatus as _SessionStatus, SessionView as _SessionView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createSession(arg0: QuizConfig): Promise<SessionView> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(to_candid_QuizConfig_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SessionView_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(to_candid_QuizConfig_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SessionView_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScore(arg0: SessionId): Promise<ScoreResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScore(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScore(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: SessionId): Promise<SessionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAnswer(arg0: SessionId, arg1: bigint, arg2: bigint): Promise<AnswerResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswer(arg0, arg1, arg2);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswer(arg0, arg1, arg2);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_QuestionKind_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionKind): QuestionKind {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionView_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionView): QuestionView {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SessionView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionView): SessionView {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScoreResult]): ScoreResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionView]): SessionView | null {
    return value.length === 0 ? null : from_candid_SessionView_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnswerResult]): AnswerResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SessionStatus;
    questions: Array<_QuestionView>;
}): {
    id: bigint;
    status: SessionStatus;
    questions: Array<QuestionView>;
} {
    return {
        id: value.id,
        status: from_candid_SessionStatus_n5(_uploadFile, _downloadFile, value.status),
        questions: from_candid_vec_n7(_uploadFile, _downloadFile, value.questions)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    kind: _QuestionKind;
    prompt: string;
    options: Array<string>;
    pokemonId: bigint;
}): {
    id: bigint;
    kind: QuestionKind;
    prompt: string;
    options: Array<string>;
    pokemonId: bigint;
} {
    return {
        id: value.id,
        kind: from_candid_QuestionKind_n10(_uploadFile, _downloadFile, value.kind),
        prompt: value.prompt,
        options: value.options,
        pokemonId: value.pokemonId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    guessMove: null;
} | {
    guessName: null;
} | {
    guessType: null;
}): QuestionKind {
    return "guessMove" in value ? QuestionKind.guessMove : "guessName" in value ? QuestionKind.guessName : "guessType" in value ? QuestionKind.guessType : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
}): SessionStatus {
    return "active" in value ? SessionStatus.active : "completed" in value ? SessionStatus.completed : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestionView>): Array<QuestionView> {
    return value.map((x)=>from_candid_QuestionView_n8(_uploadFile, _downloadFile, x));
}
function to_candid_QuizConfig_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizConfig): _QuizConfig {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generation?: Generation;
    questionCount: bigint;
}): {
    generation: [] | [_Generation];
    questionCount: bigint;
} {
    return {
        generation: value.generation ? candid_some(value.generation) : candid_none(),
        questionCount: value.questionCount
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
